### ISSUE TITLE
Crash with Glide 4.4

### ISSUE THREAD

**Issue by frankenten13** [huzhenjie/RichTextEditor#5]
Hi huzhenjie, good lib but when i update Glide to 4.4, with content <img> in .fromHtml, app crash. Can you fix that. Thanks

>     java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.nhatcuong.eoffice.debug-1/split_lib_dependencies_apk.apk:classes2.dex)
>                                                                                  at com.scrat.app.richtext.img.GlideImageGeter.getDrawable(GlideImageGeter.java:62)
>                                                                                  at android.text.HtmlToSpannedConverter.startImg(Html.java:1134)
>                                                                                  at android.text.HtmlToSpannedConverter.handleStartTag(Html.java:847)
>                                                                                  at android.text.HtmlToSpannedConverter.startElement(Html.java:1221)
>                                                                                  at org.ccil.cowan.tagsoup.Parser.push(Parser.java:795)
>                                                                                  at org.ccil.cowan.tagsoup.Parser.rectify(Parser.java:1062)
>                                                                                  at org.ccil.cowan.tagsoup.Parser.stage(Parser.java:1027)
>                                                                                  at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:632)
>                                                                                  at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:450)
>                                                                                  at android.text.HtmlToSpannedConverter.convert(Html.java:758)
>                                                                                  at android.text.Html.fromHtml(Html.java:245)
>                                                                                  at android.text.Html.fromHtml(Html.java:219)
>                                                                                  at com.scrat.app.richtext.parser.HtmlParser.fromHtml(HtmlParser.java:19)

**Comment by huzhenjie** [comment]
fix...

Upgrade the lib version

```
compile 'com.github.huzhenjie:RichTextEditor:1.0.3'
```

btw:

Glide version support to `4.3.0`
